export type Locale = 'en' | 'id'

/**
 * UI strings for the EN/ID toggle. Data (card names, groups, releases) stays
 * as-is in both locales.
 */
export const STRINGS: Record<Locale, Record<string, string>> = {
  en: {
    'aria.language': 'Switch language',
    'aria.navPrimary': 'Primary navigation',
    'aria.footerNav': 'Footer navigation',
    'aria.mobileNav': 'Mobile navigation',
    'aria.openPalette': 'Open command palette',
    'aria.switchLight': 'Switch to light mode',
    'aria.switchDark': 'Switch to dark mode',
    'footer.browse': 'Browse',
    'nav.browse': 'Catalog',
    'nav.groups': 'Groups',
    'nav.cardTypes': 'Card Types',
    'nav.releases': 'Releases',
    'nav.collection': 'Collection',
    'nav.shop': 'Shop',
    'nav.status': 'Status',
    'nav.back': 'Back',
    'search.placeholder': 'Search member, album, photocard...',
    'search.aria': 'Search photocards',
    'home.searchPlaceholder': 'Search member, album, card type...',
    'home.searchAria': 'Search member, album, card type',
    'home.shopTitle': 'Storefront & TikTok videos',
    'home.shopDesc': 'Buy photocards on Shopee / Tokopedia, or watch our latest videos.',
    'home.shopCta': 'Open Shop',
    'footer.tagline': 'K-pop photocard catalog & collection tracker.',
    'footer.copyright': 'Copyright by',
    'footer.dataBasedOn': 'Data based on',
    'footer.tracker': 'K-Pop Photocard Tracker',
    'sync.synced': 'Synced',
    'sync.cards': 'cards',
    'sync.failed': 'Sync failed',
    'sync.partial': 'Sync partial',
    'sync.stuck': 'Sync stuck since',
    'tab.home': 'Home',
    'tab.catalog': 'Catalog',
    'tab.groups': 'Groups',
    'tab.collection': 'Collection',
    'home.eyebrow': 'K-pop photocard database',
    'home.heroDescA': 'Explore album PCs, POBs, lucky draws and special photocards — by group, member, album, and market reference from ',
    'cardTypes.eyebrow': 'Explore by card type',
    'cardTypes.title': 'What kind of card is it?',
    'cardTypes.all': 'All card types',
    'releases.eyebrow': 'Explore releases',
    'releases.title': 'Albums & releases',
    'releases.all': 'All releases',
    'releases.cards': 'cards',
    'trending.title': 'Trending Photocards',
    'viewAll': 'View all',
    'browseAll': 'Browse all',
    'empty.noCards': 'No photocards found.',
    'empty.hint': 'Try another group or check back after the daily sync.',
    'empty.browseAll': 'Browse all photocards',
    'groups.eyebrow': 'Explore groups',
    'groups.title': 'Browse by group',
    'groups.open': 'Open catalog',
    'groups.desc.ive': 'Album pulls, POBs, and fan-signed cards.',
    'groups.desc.aespa': 'Tour merch, lucky draws, and essentials.',
    'groups.desc.h2h': 'Fresh releases tracked from Pocamarket.',
    'movers.eyebrow': 'Price movers',
    'movers.title': 'Biggest changes since yesterday’s sync',
    'movers.drops': 'Biggest drops',
    'movers.risers': 'Biggest risers',
    'movers.vs': '· latest vs previous price',
    'palette.placeholder': 'Search photocards or jump to a page…',
    'palette.searching': 'Searching…',
    'palette.noResults': 'No photocards found for',
    'palette.cards': 'Photocards',
    'palette.goto': 'Go to',
    'palette.nav.home': 'Home',
    'palette.nav.browse': 'Browse photocards',
    'palette.nav.releases': 'Releases timeline',
    'palette.nav.collection': 'My collection',
    'palette.nav.wishlist': 'Wishlist',
    'palette.nav.shop': 'Shop',
    'palette.nav.status': 'Sync status',
    'palette.open': 'Open',
    'palette.navigate': 'navigate',
    'palette.close': 'close',
    'browse.title': 'Photocard Catalog',
    'browse.loading': 'Loading…',
    'browse.eyebrow': 'Catalog',
    'browse.cardCount': 'cards',
    'browse.dataSource': 'Market reference data from',
    'browse.allStores': 'All stores',
    'browse.allTypes': 'All types',
    'browse.allMembers': 'All',
    'browse.storeLabel': 'Store',
    'browse.typeLabel': 'Card Type',
    'browse.memberLabel': 'Member',
    'browse.priceLabel': 'Price (IDR)',
    'browse.priceMin': 'Min',
    'browse.priceMax': 'Max',
    'browse.priceMinAria': 'Minimum price in IDR',
    'browse.priceMaxAria': 'Maximum price in IDR',
    'browse.clear': 'Clear filters',
    'browse.clearAll': 'Clear all',
    'browse.clearMobile': 'Clear',
    'browse.showResults': 'Show results',
    'browse.filters': 'Filters',
    'browse.filtersDesc': 'Narrow results by member, card type, and price.',
    'browse.empty.title': 'No photocards match these filters.',
    'browse.empty.hint': 'Try another group, member, or card type.',
    'browse.error.title': 'Unable to load photocards.',
    'browse.error.hint': 'Please try again.',
    'browse.error.retry': 'Retry',
    'browse.search.placeholder': 'Search member, group, album, card type, store...',
    'browse.search.aria': 'Search photocards',
    'browse.sort.aria': 'Sort',
    'browse.sort.popular': 'Popular',
    'browse.sort.recent': 'Recent',
    'browse.sort.priceAsc': 'Price: low to high',
    'browse.sort.priceDesc': 'Price: high to low',
    'browse.sort.stock': 'Most in stock',
    'browse.sort.name': 'Name A-Z',
    'browse.sort.wishlist': 'Most wishlisted',
    'browse.groupLabel': 'Group',
    'browse.memberChipAll': 'All',
    'browse.activeFilters': '{count} filters',
    'browse.prev': 'Prev',
    'browse.next': 'Next',
    'browse.pageOf': 'Page {current} of {total}',
    'browse.pageOfCards': 'Page {current} of {total} · {count} cards',
    'browse.stores.empty': 'No store data yet.',
    'browse.member.aria': 'Clear member {name}',
    'browse.cardType.aria': 'Clear card type {name}',
    'browse.release.aria': 'Clear release filter',
    'browse.store.aria': 'Clear store {name}',
    'browse.price.aria': 'Clear price filter',
    'card.type': 'Type',
    'card.group': 'Group',
    'card.member': 'Member',
    'card.albumRelease': 'Album / release',
    'card.store': 'Store',
    'card.event': 'Event',
    'card.listedAs': 'Listed as',
    'card.marketReference': 'Market reference',
    'card.dataSource': 'Data source · Pocamarket',
    'card.notAvailable': 'Not available',
    'card.viewOnPocamarket': 'View on Pocamarket',
    'card.wishlist': 'Wishlist',
    'card.wishlisted': 'Wishlisted',
    'card.wishAddAria': 'Add to wishlist',
    'card.wishRemoveAria': 'Remove from wishlist',
    'card.addToCollection': 'Add to Collection',
    'card.inCollection': 'In Collection',
    'card.whatIsThis': 'What is this?',
    'card.whatIsType': 'What is {type}?',
    'card.browseMore': 'Browse more {type}',
    'card.priceHistory': 'Price History',
    'card.priceHistoryEmpty': "Price history isn't available for this card yet.",
    'card.priceHistoryLow': 'Low: ${price}',
    'card.priceHistoryHigh': 'High: ${price}',
    'card.priceChangeSince': 'since last snapshot',
    'card.info.title': 'Card information',
    'card.release.title': 'Release information',
    'card.release.source': 'Source · {source}',
    'card.release.released': 'Released {date}',
    'card.release.tracks': 'Tracks',
    'card.release.moreTracks': '+ {count} more tracks',
    'card.addDialog.title': 'Add to Collection',
    'card.addDialog.desc': 'Save this photocard to your owned collection. Use the heart button for wishlist.',
    'card.addDialog.priceLabel': 'Bought Price (USD)',
    'card.addDialog.pricePlaceholder': 'Optional',
    'card.addDialog.cancel': 'Cancel',
    'card.addDialog.add': 'Add',
    'card.addDialog.adding': 'Adding...',
    'card.error.title': 'Unable to load this photocard.',
    'card.error.back': 'Back to browse',
    'card.notFound': 'Photocard not found.',
    'card.unableLoad': 'Unable to load this photocard.',
    'card.noType': 'Album',
    'blurb.Album': 'An Album PC is a photocard included inside a studio album or album package. It is part of the standard release and is obtained by purchasing the album.',
    'blurb.POB': 'A POB (Pre-Order Benefit) is a photocard distributed as a bonus during an album pre-order period. Each store or platform usually issues its own POB version.',
    'blurb.Lucky Draw': 'A Lucky Draw card is a photocard given out through an event where eligible orders are entered into a draw. Availability is limited to the event period.',
    'blurb.MD': 'An MD card is a photocard sold as part of official merchandise, such as a pop-up store item, tour goods, or a fan kit.',
    'blurb.Fan Meeting': 'A Fan Meeting card is a photocard distributed at or related to a fan meeting event, often as an attendance or participation benefit.',
    "blurb.Season's Greetings": "A Season's Greetings card is a photocard included with a seasonal calendar or diary set released once a year.",
    'blurb.Concert': 'A Concert card is a photocard connected to a concert or world tour, such as a venue benefit, merch purchase reward, or event handout.',
    'blurb.Trading Card': 'A Trading Card is a photocard released as part of an official trading card set rather than an album or event benefit.',
    'blurb.Pop-up': 'A Pop-up card is a photocard issued through a temporary pop-up store or brand activation during its operating period.',
    'blurb.Fan Club': 'A Fan Club card is a photocard included with an official fan club membership kit or renewal benefit.',
    'blurb.Fansign': 'A Fansign card is a photocard obtained through an album purchase that enters the buyer into a fansign or video call event.',
    'blurb.Broadcast': 'A Broadcast card is a photocard released through a TV music show broadcast, usually given as an attendance or participation benefit.',
    'blurb.Event': 'An Event card is a photocard distributed through a specific promotion, raffle, or limited-time event.',
    'auth.login': 'Log in',
    'auth.logout': 'Log out',
    'auth.register': 'Create account',
    'auth.username': 'Username',
    'auth.password': 'Password',
    'auth.confirmPassword': 'Confirm password',
    'auth.noAccount': "Don't have an account?",
    'auth.haveAccount': 'Already have an account?',
    'auth.switchToRegister': 'Create one',
    'auth.switchToLogin': 'Log in',
    'auth.loginTitle': 'Welcome back',
    'auth.loginDesc': 'Log in to keep your wishlist and collection safe.',
    'auth.registerTitle': 'Create your account',
    'auth.registerDesc': 'Save your wishlist and owned cards to your own account.',
    'auth.err.usernameFormat': 'Username: 3–20 letters, numbers or underscores.',
    'auth.err.passwordLength': 'Password must be at least 8 characters.',
    'auth.err.passwordMatch': 'Passwords do not match.',
    'auth.collectionLocked': 'Log in to view your collection',
    'auth.collectionLockedDesc': 'Your wishlist and owned cards are tied to your account.',
    'auth.loginFirst': 'Log in first to save cards to your collection.',
    'auth.loggingIn': 'Logging in…',
    'auth.creating': 'Creating account…',
    'auth.brandTitle': 'Your photocard binder, everywhere.',
    'auth.brandDesc': 'Save wishlists, track owned cards, and watch market prices — synced every day.',
    'auth.benefitWishlist': 'Personal wishlist on your own account',
    'auth.benefitBinder': 'Owned cards with live market value',
    'auth.benefitSync': 'Daily price sync at 00:00 WIB',
    'auth.passwordHint': 'Minimum 8 characters.',
    'auth.loginNote': 'First time here? Switch to the “Create account” tab above to register.',
    'auth.showPassword': 'Show password',
    'auth.hidePassword': 'Hide password',
    'status.errors': 'Recent errors',
    'status.errorsEmpty': 'No errors recorded.',
    'status.loginForErrors': 'Log in to view the error log.',
    'status.forbiddenTitle': 'Admins only',
    'status.forbiddenDesc': 'This page is only available to the admin account.',
    'status.backHome': 'Back to home',
    'status.scopeServer': 'server',
    'status.scopeClient': 'client',
    'releases.timeline.eyebrow': 'Comeback timeline',
    'releases.timeline.desc': 'Every album, single and special release in the catalog, newest first. Release dates come from MusicBrainz and Apple\u00A0Music; open a release to see its photocards.',
    'releases.timeline.error': 'Unable to load releases.',
    'releases.timeline.datedOne': 'release with a date',
    'releases.timeline.datedMany': 'releases with a date',
    'releases.timeline.undatedSuffix': 'without one',
    'releases.timeline.yearOne': 'release',
    'releases.timeline.yearMany': 'releases',
    'releases.timeline.datePending': 'Date pending',
    'releases.timeline.coverAlt': '{name} cover',
    'releases.timeline.empty': 'No releases found.',
    'releases.noCardsYet': 'No cards yet',
    'releaseDetail.notFound': 'Release not found.',
    'releaseDetail.notFoundHint': 'It may have been renamed by the latest sync.',
    'releaseDetail.browseCatalog': 'Browse catalog',
    'releaseDetail.error': 'Unable to load this release.',
    'releaseDetail.eyebrow': 'Release · Photocards',
    'releaseDetail.members': 'members',
    'releaseDetail.cheapest': 'Cheapest card',
    'releaseDetail.marketRef': 'market reference',
    'releaseDetail.seeInCatalog': 'See in catalog',
    'releaseDetail.cardTypes': 'Card types',
    'releaseDetail.membersTitle': 'Members',
    'releaseDetail.tracklist': 'Tracklist',
    'releaseDetail.cardOne': 'card',
    'releaseDetail.cardMany': 'cards',
    'releaseDetail.noPhotocardsYet': 'No photocards yet',
    'releaseDetail.empty': 'No photocards listed.',
    'releaseDetail.emptyHint': 'Check back after the daily Pocamarket sync.',
    'releaseDetail.loadMore': 'Load more',
    'groupDetail.eyebrow': 'Group · Photocard catalog',
    'groupDetail.members': 'members',
    'groupDetail.releases': 'releases',
    'groupDetail.marketRef': 'Market reference · Pocamarket',
    'groupDetail.error': 'Unable to load this group.',
    'groupDetail.membersTitle': 'Members',
    'groupDetail.cardTypes': 'Card types',
    'groupDetail.countsNote': 'Counts from the full catalog.',
    'groupDetail.latestEyebrow': 'Latest',
    'groupDetail.latestTitle': 'Newest {group} cards',
    'groupDetail.latestEmpty': 'No cards indexed for this group yet.',
    'groupDetail.releasesEyebrow': 'Albums / releases',
    'groupDetail.releasesTitle': 'Where these cards come from',
    'shop.eyebrow': 'HIBIKISHOP Store',
    'shop.title': 'Storefront & TikTok',
    'shop.desc': 'Shop HIBIKISHOP photocards through Shopee, Tokopedia, or TikTok — plus our latest videos.',
    'shop.connected': 'TikTok account connected. Loading videos…',
    'shop.connectError': 'Failed to connect TikTok: {error}',
    'shop.productsTitle': 'Storefront products',
    'shop.refresh': 'Refresh',
    'shop.productsEmpty': 'No products from the TikTok Shop API yet',
    'shop.productsEmptyHint': 'Connect the Seller/Partner API to show the storefront automatically.',
    'shop.productsNoteConfig': 'TikTok Shop products activate once TIKTOK_SHOP_ACCESS_TOKEN is set (Partner Center).',
    'shop.productsNoteNone': 'No active products.',
    'shop.productsNoteError': 'Failed to load TikTok Shop products.',
    'shop.buy': 'Buy',
    'shop.featuredEyebrow': 'Storefront',
    'shop.featuredTitle': 'Featured collections',
    'shop.videosTitle': 'Videos from @hibikis13',
    'shop.openTikTok': 'Open TikTok',
    'shop.connectTitle': 'Connect TikTok account @hibikis13',
    'shop.connectDescA': 'Official TikTok OAuth (scope ',
    'shop.connectDescB': ') — pulls every public video onto this page.',
    'shop.connect': 'Connect TikTok',
    'shop.videosEmpty': 'No videos synced yet',
    'shop.videosEmptyHint': 'Connect a TikTok account to pull in all videos.',
    'shop.videosError': 'Not connected to TikTok yet',
    'shop.untitled': 'Untitled',
    'shop.views': 'views',
    'shop.videoAlt': 'TikTok video',
    'shop.liveEmbed': 'Live profile embed',
    'shop.loading': 'Loading TikTok…',
    'shop.ogDescription': 'HIBIKISHOP storefront — buy photocards on Shopee & Tokopedia, watch the latest TikTok videos.',
    'shop.ctaShopee': 'Buy on Shopee',
    'shop.ctaTokopedia': 'Buy on Tokopedia',
    'shop.ctaTiktok': 'Check on TikTok',
    'shop.ctaChat': 'Chat / Pre-order',
    'shop.ctaStore': 'Open storefront',
    'shop.p.ive.name': 'IVE Photocards',
    'shop.p.ive.desc': 'Album pulls, POBs, and fan-signed cards — ready to ship.',
    'shop.p.ive.badge': 'Popular',
    'shop.p.aespa.name': 'aespa Photocards',
    'shop.p.aespa.desc': 'Tour merch, lucky draws, and everyday essentials.',
    'shop.p.aespa.badge': 'Restock',
    'shop.p.h2h.name': 'Hearts2Hearts',
    'shop.p.h2h.desc': 'Fresh releases and new drops tracked daily.',
    'shop.p.h2h.badge': 'New',
    'shop.p.bundle.name': 'Bundle & Mystery',
    'shop.p.bundle.desc': 'Curated bundles and blind packs for collectors.',
    'shop.p.topup.name': 'Pre-order & Top-up',
    'shop.p.topup.desc': 'Open PO for albums and limited photocard sets.',
    'shop.p.all.name': 'Full Store',
    'shop.p.all.desc': 'Browse every item in the HIBIKISHOP storefront.',
    'error.notFoundTitle': 'Page not found',
    'error.notFoundDesc': "The page you're looking for doesn't exist or has moved.",
    'error.backHome': 'Go back home',
    'collection.eyebrow': 'Binder',
    'collection.title': 'My Collection',
    'collection.desc': 'Your digital photocard binder — cards you own and want.',
    'collection.ownedValue': 'owned value',
    'collection.wishlist': 'wishlist',
    'collection.all': 'All',
    'collection.tabOwned': 'Owned',
    'collection.tabWishlist': 'Wishlist',
    'collection.filterAria': 'Filter collection by card type',
    'collection.error': 'Unable to load your collection. Please try again.',
    'collection.emptyType': 'No {type} cards',
    'collection.emptyWishlist': 'Your wishlist is empty',
    'collection.emptyOwned': 'Nothing owned yet',
    'collection.emptyBinder': 'Your binder is empty',
    'collection.emptyTypeHint': 'Try another card type, or add more cards to this binder.',
    'collection.emptyHint': 'Start adding photocards to build your collection.',
    'collection.showAllTypes': 'Show all types',
    'collection.browsePhotocards': 'Browse Photocards',
    'collection.progressLabel': 'collected',
    'collection.ownedLabel': 'owned',
    'collection.progressAria': '{group} collection progress',
    'collection.badgeOwned': 'Owned',
    'collection.badgeWishlist': 'Wishlist',
    'collection.removeAria': 'Remove {name} from collection',
    'collection.removeAriaWishlist': 'Remove {name} from wishlist',
    'collection.other': 'Other',
    'collection.removeTitleCollection': 'Remove from collection?',
    'collection.removeTitleWishlist': 'Remove from wishlist?',
    'collection.removeDescNamed': '“{name}” will be removed. You can add it again later.',
    'collection.removeDesc': 'This card will be removed. You can add it again later.',
    'collection.removing': 'Removing…',
    'collection.remove': 'Remove',
    'status.systemEyebrow': 'System status',
    'status.desc': 'Daily Pocamarket sync (00:00 WIB) and its run history — what ran, how long it took, and whether anything failed.',
    'status.tracked': 'photocards tracked',
    'status.lastDataUpdate': 'Last data update',
    'status.latestRefresh': 'latest card refresh',
    'status.lastRun': 'Last run',
    'status.history': 'History',
    'status.recentRuns': 'Recent runs',
    'status.lastOf': 'last {count} of 30',
    'status.emptyTitle': 'No sync runs recorded yet.',
    'status.emptyHint': 'History appears after the first scheduled run at 00:00 WIB.',
    'status.groupChipCards': '{group}: {count} cards',
    'status.failed': 'failed',
    'status.monitoring': 'Monitoring',
    'status.stack': 'Stack',
  },
  id: {
    'aria.language': 'Ganti bahasa',
    'aria.navPrimary': 'Navigasi utama',
    'aria.footerNav': 'Navigasi footer',
    'aria.mobileNav': 'Navigasi seluler',
    'aria.openPalette': 'Buka command palette',
    'aria.switchLight': 'Ganti ke mode terang',
    'aria.switchDark': 'Ganti ke mode gelap',
    'footer.browse': 'Jelajahi',
    'nav.browse': 'Katalog',
    'nav.groups': 'Grup',
    'nav.cardTypes': 'Jenis Kartu',
    'nav.releases': 'Rilisan',
    'nav.collection': 'Koleksi',
    'nav.shop': 'Toko',
    'nav.status': 'Status',
    'nav.back': 'Kembali',
    'search.placeholder': 'Cari member, album, photocard...',
    'search.aria': 'Cari photocard',
    'home.searchPlaceholder': 'Cari member, album, jenis kartu...',
    'home.searchAria': 'Cari member, album, jenis kartu',
    'home.shopTitle': 'Etalase & video TikTok',
    'home.shopDesc': 'Beli photocard di Shopee / Tokopedia, atau tonton konten terbaru kami.',
    'home.shopCta': 'Buka Shop',
    'footer.tagline': 'Katalog & pelacak koleksi photocard K-pop.',
    'footer.copyright': 'Hak cipta oleh',
    'footer.dataBasedOn': 'Berdasarkan data',
    'footer.tracker': 'Pelacak Photocard K-pop',
    'sync.synced': 'Tersinkron',
    'sync.cards': 'kartu',
    'sync.failed': 'Sinkron gagal',
    'sync.partial': 'Sinkron sebagian',
    'sync.stuck': 'Sinkron macet sejak',
    'tab.home': 'Beranda',
    'tab.catalog': 'Katalog',
    'tab.groups': 'Grup',
    'tab.collection': 'Koleksi',
    'home.eyebrow': 'Database photocard K-pop',
    'home.heroDescA': 'Jelajahi album PC, POB, lucky draw, dan photocard spesial — per grup, member, album, serta referensi pasar dari ',
    'cardTypes.eyebrow': 'Jelajahi jenis kartu',
    'cardTypes.title': 'Jenis kartu seperti apa?',
    'cardTypes.all': 'Semua jenis kartu',
    'releases.eyebrow': 'Jelajahi rilisan',
    'releases.title': 'Album & rilisan',
    'releases.all': 'Semua rilisan',
    'releases.cards': 'kartu',
    'trending.title': 'Photocard populer',
    'viewAll': 'Lihat semua',
    'browseAll': 'Lihat semua',
    'empty.noCards': 'Photocard tidak ditemukan.',
    'empty.hint': 'Coba grup lain atau cek kembali setelah sinkronisasi harian.',
    'empty.browseAll': 'Jelajahi semua photocard',
    'groups.eyebrow': 'Jelajahi grup',
    'groups.title': 'Telusuri per grup',
    'groups.open': 'Buka katalog',
    'groups.desc.ive': 'Album pull, POB, dan kartu fan-signed.',
    'groups.desc.aespa': 'Merch tur, lucky draw, dan kebutuhan wajib.',
    'groups.desc.h2h': 'Rilisan baru yang dilacak dari Pocamarket.',
    'movers.eyebrow': 'Pergerakan harga',
    'movers.title': 'Perubahan terbesar sejak sinkron kemarin',
    'movers.drops': 'Turun paling besar',
    'movers.risers': 'Naik paling besar',
    'movers.vs': '· harga terbaru vs sebelumnya',
    'palette.placeholder': 'Cari photocard atau buka halaman…',
    'palette.searching': 'Mencari…',
    'palette.noResults': 'Photocard tidak ditemukan untuk',
    'palette.cards': 'Photocards',
    'palette.goto': 'Buka halaman',
    'palette.nav.home': 'Beranda',
    'palette.nav.browse': 'Jelajahi photocard',
    'palette.nav.releases': 'Timeline rilisan',
    'palette.nav.collection': 'Koleksi saya',
    'palette.nav.wishlist': 'Wishlist',
    'palette.nav.shop': 'Toko',
    'palette.nav.status': 'Status sinkronisasi',
    'palette.open': 'Buka',
    'palette.navigate': 'navigasi',
    'palette.close': 'tutup',
    'browse.title': 'Katalog Photocard',
    'browse.loading': 'Memuat…',
    'browse.eyebrow': 'Katalog',
    'browse.cardCount': 'kartu',
    'browse.dataSource': 'Data referensi pasar dari',
    'browse.allStores': 'Semua toko',
    'browse.allTypes': 'Semua jenis',
    'browse.allMembers': 'Semua',
    'browse.storeLabel': 'Toko',
    'browse.typeLabel': 'Jenis Kartu',
    'browse.memberLabel': 'Member',
    'browse.priceLabel': 'Harga (IDR)',
    'browse.priceMin': 'Min',
    'browse.priceMax': 'Maks',
    'browse.priceMinAria': 'Harga minimum dalam IDR',
    'browse.priceMaxAria': 'Harga maksimum dalam IDR',
    'browse.clear': 'Hapus filter',
    'browse.clearAll': 'Hapus semua',
    'browse.clearMobile': 'Hapus',
    'browse.showResults': 'Tampilkan hasil',
    'browse.filters': 'Filter',
    'browse.filtersDesc': 'Saring hasil berdasarkan member, jenis kartu, dan harga.',
    'browse.empty.title': 'Tidak ada photocard yang cocok dengan filter ini.',
    'browse.empty.hint': 'Coba grup, member, atau jenis kartu lain.',
    'browse.error.title': 'Gagal memuat photocard.',
    'browse.error.hint': 'Silakan coba lagi.',
    'browse.error.retry': 'Coba lagi',
    'browse.search.placeholder': 'Cari member, grup, album, jenis kartu, toko...',
    'browse.search.aria': 'Cari photocard',
    'browse.sort.aria': 'Urutkan',
    'browse.sort.popular': 'Populer',
    'browse.sort.recent': 'Terbaru',
    'browse.sort.priceAsc': 'Harga: rendah ke tinggi',
    'browse.sort.priceDesc': 'Harga: tinggi ke rendah',
    'browse.sort.stock': 'Stok terbanyak',
    'browse.sort.name': 'Nama A-Z',
    'browse.sort.wishlist': 'Paling banyak di-wishlist',
    'browse.groupLabel': 'Grup',
    'browse.memberChipAll': 'Semua',
    'browse.activeFilters': '{count} filter',
    'browse.prev': 'Sebelumnya',
    'browse.next': 'Berikutnya',
    'browse.pageOf': 'Halaman {current} dari {total}',
    'browse.pageOfCards': 'Halaman {current} dari {total} · {count} kartu',
    'browse.stores.empty': 'Belum ada data toko.',
    'browse.member.aria': 'Hapus filter member {name}',
    'browse.cardType.aria': 'Hapus filter jenis kartu {name}',
    'browse.release.aria': 'Hapus filter rilisan',
    'browse.store.aria': 'Hapus filter toko {name}',
    'browse.price.aria': 'Hapus filter harga',
    'card.type': 'Jenis',
    'card.group': 'Grup',
    'card.member': 'Member',
    'card.albumRelease': 'Album / rilisan',
    'card.store': 'Toko',
    'card.event': 'Event',
    'card.listedAs': 'Terdaftar sebagai',
    'card.marketReference': 'Referensi pasar',
    'card.dataSource': 'Sumber data · Pocamarket',
    'card.notAvailable': 'Tidak tersedia',
    'card.viewOnPocamarket': 'Lihat di Pocamarket',
    'card.wishlist': 'Wishlist',
    'card.wishlisted': 'Di-wishlist',
    'card.wishAddAria': 'Tambah ke wishlist',
    'card.wishRemoveAria': 'Hapus dari wishlist',
    'card.addToCollection': 'Tambah ke Koleksi',
    'card.inCollection': 'Ada di Koleksi',
    'card.whatIsThis': 'Apa ini?',
    'card.whatIsType': 'Apa itu {type}?',
    'card.browseMore': 'Lihat {type} lainnya',
    'card.priceHistory': 'Riwayat Harga',
    'card.priceHistoryEmpty': 'Riwayat harga belum tersedia untuk kartu ini.',
    'card.priceHistoryLow': 'Terendah: ${price}',
    'card.priceHistoryHigh': 'Tertinggi: ${price}',
    'card.priceChangeSince': 'sejak pembaruan terakhir',
    'card.info.title': 'Informasi kartu',
    'card.release.title': 'Informasi rilisan',
    'card.release.source': 'Sumber · {source}',
    'card.release.released': 'Rilis {date}',
    'card.release.tracks': 'Daftar lagu',
    'card.release.moreTracks': '+ {count} lagu lainnya',
    'card.addDialog.title': 'Tambah ke Koleksi',
    'card.addDialog.desc': 'Simpan photocard ini ke koleksi milikmu. Gunakan tombol hati untuk wishlist.',
    'card.addDialog.priceLabel': 'Harga Beli (USD)',
    'card.addDialog.pricePlaceholder': 'Opsional',
    'card.addDialog.cancel': 'Batal',
    'card.addDialog.add': 'Tambah',
    'card.addDialog.adding': 'Menambahkan...',
    'card.error.title': 'Gagal memuat photocard ini.',
    'card.error.back': 'Kembali ke beranda',
    'card.notFound': 'Photocard tidak ditemukan.',
    'card.unableLoad': 'Gagal memuat photocard ini.',
    'card.noType': 'Album',
    'blurb.Album': 'Album PC adalah photocard yang disertakan di dalam album atau paket album. Bagian dari rilisan standar dan didapatkan dengan membeli album.',
    'blurb.POB': 'POB (Pre-Order Benefit) adalah photocard yang didistribusikan sebagai bonus selama masa pre-order album. Setiap toko atau platform biasanya menerbitkan versi POB sendiri.',
    'blurb.Lucky Draw': 'Kartu Lucky Draw adalah photocard yang diberikan melalui event di mana pesanan yang memenuhi syarat dimasukkan ke dalam undian. Ketersediaan terbatas selama periode event.',
    'blurb.MD': 'Kartu MD adalah photocard yang dijual sebagai bagian dari merchandise resmi, seperti item pop-up store, barang tur, atau fan kit.',
    'blurb.Fan Meeting': 'Kartu Fan Meeting adalah photocard yang didistribusikan di atau terkait event fan meeting, biasanya sebagai benefit kehadiran atau partisipasi.',
    "blurb.Season's Greetings": "Kartu Season's Greetings adalah photocard yang disertakan dengan set kalender atau buku harian musiman yang dirilis setahun sekali.",
    'blurb.Concert': 'Kartu Concert adalah photocard yang terkait dengan konser atau world tour, seperti benefit venue, reward pembelian merchandise, atau handout event.',
    'blurb.Trading Card': 'Trading Card adalah photocard yang dirilis sebagai bagian dari set kartu trading resmi, bukan dari album atau benefit event.',
    'blurb.Pop-up': 'Kartu Pop-up adalah photocard yang diterbitkan melalui toko pop-up sementara atau aktivasi brand selama periode operasionalnya.',
    'blurb.Fan Club': 'Kartu Fan Club adalah photocard yang disertakan dengan kit keanggotaan fan club resmi atau benefit perpanjangan keanggotaan.',
    'blurb.Fansign': 'Kartu Fansign adalah photocard yang didapatkan melalui pembelian album yang memasukkan pembeli ke dalam event fansign atau video call.',
    'blurb.Broadcast': 'Kartu Broadcast adalah photocard yang dirilis melalui siaran acara musik TV, biasanya diberikan sebagai benefit kehadiran atau partisipasi.',
    'blurb.Event': 'Kartu Event adalah photocard yang didistribusikan melalui promosi, undian, atau event terbatas tertentu.',
    'auth.login': 'Masuk',
    'auth.logout': 'Keluar',
    'auth.register': 'Buat akun',
    'auth.username': 'Nama pengguna',
    'auth.password': 'Kata sandi',
    'auth.confirmPassword': 'Ulangi kata sandi',
    'auth.noAccount': 'Belum punya akun?',
    'auth.haveAccount': 'Sudah punya akun?',
    'auth.switchToRegister': 'Buat akun',
    'auth.switchToLogin': 'Masuk',
    'auth.loginTitle': 'Selamat datang kembali',
    'auth.loginDesc': 'Masuk agar wishlist dan koleksimu tersimpan aman.',
    'auth.registerTitle': 'Buat akunmu',
    'auth.registerDesc': 'Simpan wishlist dan kartu yang kamu miliki ke akunmu sendiri.',
    'auth.err.usernameFormat': 'Nama pengguna: 3–20 huruf, angka, atau garis bawah.',
    'auth.err.passwordLength': 'Kata sandi minimal 8 karakter.',
    'auth.err.passwordMatch': 'Kata sandi tidak sama.',
    'auth.collectionLocked': 'Masuk untuk melihat koleksimu',
    'auth.collectionLockedDesc': 'Wishlist dan kartu yang dimiliki terikat ke akunmu.',
    'auth.loginFirst': 'Masuk dulu untuk menyimpan kartu ke koleksi.',
    'auth.loggingIn': 'Masuk…',
    'auth.creating': 'Membuat akun…',
    'auth.brandTitle': 'Binder photocard-mu, di mana saja.',
    'auth.brandDesc': 'Simpan wishlist, pantau kartu yang dimiliki, dan lihat harga pasar — sinkron setiap hari.',
    'auth.benefitWishlist': 'Wishlist pribadi di akunmu sendiri',
    'auth.benefitBinder': 'Kartu dimiliki dengan nilai pasar live',
    'auth.benefitSync': 'Sinkron harga harian jam 00.00 WIB',
    'auth.passwordHint': 'Minimal 8 karakter.',
    'auth.loginNote': 'Baru pertama kali? Buka tab “Buat akun” di atas untuk mendaftar.',
    'auth.showPassword': 'Tampilkan kata sandi',
    'auth.hidePassword': 'Sembunyikan kata sandi',
    'status.errors': 'Error terakhir',
    'status.errorsEmpty': 'Belum ada error tercatat.',
    'status.loginForErrors': 'Masuk untuk melihat log error.',
    'status.forbiddenTitle': 'Khusus admin',
    'status.forbiddenDesc': 'Halaman ini hanya tersedia untuk akun admin.',
    'status.backHome': 'Kembali ke beranda',
    'status.scopeServer': 'server',
    'status.scopeClient': 'klien',
    'releases.timeline.eyebrow': 'Timeline comeback',
    'releases.timeline.desc': 'Semua album, single, dan rilisan spesial di katalog, terbaru lebih dulu. Tanggal rilis berasal dari MusicBrainz dan Apple\u00A0Music; buka rilisan untuk melihat photocard-nya.',
    'releases.timeline.error': 'Gagal memuat rilisan.',
    'releases.timeline.datedOne': 'rilisan bertanggal',
    'releases.timeline.datedMany': 'rilisan bertanggal',
    'releases.timeline.undatedSuffix': 'tanpa tanggal',
    'releases.timeline.yearOne': 'rilisan',
    'releases.timeline.yearMany': 'rilisan',
    'releases.timeline.datePending': 'Tanggal menyusul',
    'releases.timeline.coverAlt': 'Sampul {name}',
    'releases.timeline.empty': 'Rilisan tidak ditemukan.',
    'releases.noCardsYet': 'Belum ada kartu',
    'releaseDetail.notFound': 'Rilisan tidak ditemukan.',
    'releaseDetail.notFoundHint': 'Mungkin sudah diganti namanya oleh sinkronisasi terbaru.',
    'releaseDetail.browseCatalog': 'Buka katalog',
    'releaseDetail.error': 'Gagal memuat rilisan ini.',
    'releaseDetail.eyebrow': 'Rilisan · Photocards',
    'releaseDetail.members': 'member',
    'releaseDetail.cheapest': 'Kartu termurah',
    'releaseDetail.marketRef': 'referensi pasar',
    'releaseDetail.seeInCatalog': 'Lihat di katalog',
    'releaseDetail.cardTypes': 'Jenis kartu',
    'releaseDetail.membersTitle': 'Member',
    'releaseDetail.tracklist': 'Daftar lagu',
    'releaseDetail.cardOne': 'kartu',
    'releaseDetail.cardMany': 'kartu',
    'releaseDetail.noPhotocardsYet': 'Belum ada photocard',
    'releaseDetail.empty': 'Belum ada photocard yang terdaftar.',
    'releaseDetail.emptyHint': 'Cek lagi setelah sinkronisasi harian Pocamarket.',
    'releaseDetail.loadMore': 'Muat lebih banyak',
    'groupDetail.eyebrow': 'Grup · Katalog photocard',
    'groupDetail.members': 'member',
    'groupDetail.releases': 'rilisan',
    'groupDetail.marketRef': 'Referensi pasar · Pocamarket',
    'groupDetail.error': 'Gagal memuat grup ini.',
    'groupDetail.membersTitle': 'Member',
    'groupDetail.cardTypes': 'Jenis kartu',
    'groupDetail.countsNote': 'Hitungan dari katalog penuh.',
    'groupDetail.latestEyebrow': 'Terbaru',
    'groupDetail.latestTitle': 'Kartu {group} terbaru',
    'groupDetail.latestEmpty': 'Belum ada kartu terindeks untuk grup ini.',
    'groupDetail.releasesEyebrow': 'Album / rilisan',
    'groupDetail.releasesTitle': 'Asal kartu-kartu ini',
    'shop.eyebrow': 'Toko HIBIKISHOP',
    'shop.title': 'Etalase & TikTok',
    'shop.desc': 'Belanja photocard HIBIKISHOP lewat Shopee, Tokopedia, atau TikTok — plus video terbaru dari kami.',
    'shop.connected': 'Akun TikTok berhasil terhubung. Video sedang dimuat…',
    'shop.connectError': 'Gagal konek TikTok: {error}',
    'shop.productsTitle': 'Produk etalase',
    'shop.refresh': 'Segarkan',
    'shop.productsEmpty': 'Belum ada produk dari TikTok Shop API',
    'shop.productsEmptyHint': 'Sambungkan Seller/Partner API untuk menampilkan etalase otomatis.',
    'shop.productsNoteConfig': 'Produk TikTok Shop aktif setelah TIKTOK_SHOP_ACCESS_TOKEN diisi (Partner Center).',
    'shop.productsNoteNone': 'Tidak ada produk aktif.',
    'shop.productsNoteError': 'Gagal memuat produk TikTok Shop.',
    'shop.buy': 'Beli',
    'shop.featuredEyebrow': 'Etalase',
    'shop.featuredTitle': 'Koleksi unggulan',
    'shop.videosTitle': 'Video dari @hibikis13',
    'shop.openTikTok': 'Buka TikTok',
    'shop.connectTitle': 'Hubungkan akun TikTok @hibikis13',
    'shop.connectDescA': 'OAuth resmi TikTok (scope ',
    'shop.connectDescB': ') — ambil semua video public ke halaman ini.',
    'shop.connect': 'Hubungkan TikTok',
    'shop.videosEmpty': 'Belum ada video tersinkron',
    'shop.videosEmptyHint': 'Hubungkan akun TikTok untuk mengambil semua video.',
    'shop.videosError': 'Belum terhubung ke TikTok',
    'shop.untitled': 'Tanpa judul',
    'shop.views': 'ditonton',
    'shop.videoAlt': 'Video TikTok',
    'shop.liveEmbed': 'Embed profil langsung',
    'shop.loading': 'Memuat TikTok…',
    'shop.ogDescription': 'Etalase HIBIKISHOP - beli photocard di Shopee & Tokopedia, tonton video TikTok terbaru.',
    'shop.ctaShopee': 'Beli di Shopee',
    'shop.ctaTokopedia': 'Beli di Tokopedia',
    'shop.ctaTiktok': 'Cek di TikTok',
    'shop.ctaChat': 'Chat / Pre-order',
    'shop.ctaStore': 'Buka etalase',
    'shop.p.ive.name': 'Photocard IVE',
    'shop.p.ive.desc': 'Album pull, POB, dan kartu tanda tangan fans — siap kirim.',
    'shop.p.ive.badge': 'Populer',
    'shop.p.aespa.name': 'Photocard aespa',
    'shop.p.aespa.desc': 'Merch tur, lucky draw, dan kebutuhan sehari-hari.',
    'shop.p.aespa.badge': 'Restock',
    'shop.p.h2h.name': 'Hearts2Hearts',
    'shop.p.h2h.desc': 'Rilisan baru dan drop terbaru setiap hari.',
    'shop.p.h2h.badge': 'Baru',
    'shop.p.bundle.name': 'Bundle & Misteri',
    'shop.p.bundle.desc': 'Bundle pilihan dan blind pack untuk kolektor.',
    'shop.p.topup.name': 'Pre-order & Top-up',
    'shop.p.topup.desc': 'PO terbuka untuk album dan set photocard terbatas.',
    'shop.p.all.name': 'Etalase Lengkap',
    'shop.p.all.desc': 'Jelajahi semua item di etalase HIBIKISHOP.',
    'error.notFoundTitle': 'Halaman tidak ditemukan',
    'error.notFoundDesc': 'Halaman yang kamu cari tidak ada atau sudah dipindah.',
    'error.backHome': 'Kembali ke beranda',
    'collection.eyebrow': 'Binder',
    'collection.title': 'Koleksi Saya',
    'collection.desc': 'Binder photocard digitalmu — kartu yang kamu miliki dan inginkan.',
    'collection.ownedValue': 'nilai kepemilikan',
    'collection.wishlist': 'wishlist',
    'collection.all': 'Semua',
    'collection.tabOwned': 'Dimiliki',
    'collection.tabWishlist': 'Wishlist',
    'collection.filterAria': 'Saring koleksi berdasarkan jenis kartu',
    'collection.error': 'Gagal memuat koleksimu. Silakan coba lagi.',
    'collection.emptyType': 'Tidak ada kartu {type}',
    'collection.emptyWishlist': 'Wishlist-mu masih kosong',
    'collection.emptyOwned': 'Belum ada yang dimiliki',
    'collection.emptyBinder': 'Binder-mu masih kosong',
    'collection.emptyTypeHint': 'Coba jenis kartu lain, atau tambahkan kartu ke binder ini.',
    'collection.emptyHint': 'Mulai tambahkan photocard untuk membangun koleksimu.',
    'collection.showAllTypes': 'Tampilkan semua jenis',
    'collection.browsePhotocards': 'Jelajahi Photocard',
    'collection.progressLabel': 'terkumpul',
    'collection.ownedLabel': 'dimiliki',
    'collection.progressAria': 'Progres koleksi {group}',
    'collection.badgeOwned': 'Dimiliki',
    'collection.badgeWishlist': 'Wishlist',
    'collection.removeAria': 'Hapus {name} dari koleksi',
    'collection.removeAriaWishlist': 'Hapus {name} dari wishlist',
    'collection.other': 'Lainnya',
    'collection.removeTitleCollection': 'Hapus dari koleksi?',
    'collection.removeTitleWishlist': 'Hapus dari wishlist?',
    'collection.removeDescNamed': '“{name}” akan dihapus. Kamu bisa menambahkannya lagi nanti.',
    'collection.removeDesc': 'Kartu ini akan dihapus. Kamu bisa menambahkannya lagi nanti.',
    'collection.removing': 'Menghapus…',
    'collection.remove': 'Hapus',
    'status.systemEyebrow': 'Status sistem',
    'status.desc': 'Sinkronisasi harian Pocamarket (00:00 WIB) dan riwayatnya — apa yang dijalankan, berapa lama, dan apakah ada yang gagal.',
    'status.tracked': 'photocard terlacak',
    'status.lastDataUpdate': 'Pembaruan data terakhir',
    'status.latestRefresh': 'pembaruan kartu terakhir',
    'status.lastRun': 'Run terakhir',
    'status.history': 'Riwayat',
    'status.recentRuns': 'Run terbaru',
    'status.lastOf': '{count} terakhir dari 30',
    'status.emptyTitle': 'Belum ada run sinkronisasi yang tercatat.',
    'status.emptyHint': 'Riwayat muncul setelah run terjadwal pertama pukul 00:00 WIB.',
    'status.groupChipCards': '{group}: {count} kartu',
    'status.failed': 'gagal',
    'status.monitoring': 'Pemantauan',
    'status.stack': 'Stack',
  },
}
