export type Locale = 'en' | 'id'

/**
 * UI strings for the EN/ID toggle. Data (card names, groups, releases) stays
 * as-is in both locales.
 */
export const STRINGS: Record<Locale, Record<string, string>> = {
  en: {
    'aria.language': 'Switch language',
    'footer.browse': 'Browse',
    'nav.browse': 'Catalog',
    'nav.groups': 'Groups',
    'nav.cardTypes': 'Card Types',
    'nav.releases': 'Releases',
    'nav.collection': 'Collection',
    'nav.shop': 'Shop',
    'nav.status': 'Status',
    'search.placeholder': 'Search member, album, photocard...',
    'home.searchPlaceholder': 'Search member, album, card type...',
    'footer.tagline': 'K-pop photocard catalog & collection tracker.',
    'footer.copyright': 'Copyright by',
    'footer.dataBasedOn': 'Data based on',
    'footer.tracker': 'K-Pop Photocard Tracker',
    'sync.synced': 'Synced',
    'sync.cards': 'cards',
    'sync.failed': 'Sync failed',
    'sync.partial': 'Sync partial',
    'sync.stuck': 'Sync stuck since',
    'tab.home': 'Home',
    'tab.catalog': 'Catalog',
    'tab.groups': 'Groups',
    'tab.collection': 'Collection',
    'home.eyebrow': 'K-pop photocard database',
    'home.heroDescA': 'Explore album PCs, POBs, lucky draws and special photocards — by group, member, album, and market reference from ',
    'cardTypes.eyebrow': 'Explore by card type',
    'cardTypes.title': 'What kind of card is it?',
    'cardTypes.all': 'All card types',
    'releases.eyebrow': 'Explore releases',
    'releases.title': 'Albums & releases',
    'releases.all': 'All releases',
    'releases.cards': 'cards',
    'trending.title': 'Trending Photocards',
    'viewAll': 'View all',
    'browseAll': 'Browse all',
    'empty.noCards': 'No photocards found.',
    'empty.hint': 'Try another group or check back after the daily sync.',
    'empty.browseAll': 'Browse all photocards',
    'groups.eyebrow': 'Explore groups',
    'groups.title': 'Browse by group',
    'groups.open': 'Open catalog',
    'groups.desc.ive': 'Album pulls, POBs, and fan-signed cards.',
    'groups.desc.aespa': 'Tour merch, lucky draws, and essentials.',
    'groups.desc.h2h': 'Fresh releases tracked from Pocamarket.',
    'movers.eyebrow': 'Price movers',
    'movers.title': 'Biggest changes since yesterday’s sync',
    'movers.drops': 'Biggest drops',
    'movers.risers': 'Biggest risers',
    'movers.vs': '· latest vs previous price',
    'palette.placeholder': 'Search photocards or jump to a page…',
    'palette.searching': 'Searching…',
    'palette.noResults': 'No photocards found for',
    'palette.cards': 'Photocards',
    'palette.goto': 'Go to',
    'palette.nav.home': 'Home',
    'palette.nav.browse': 'Browse photocards',
    'palette.nav.releases': 'Releases timeline',
    'palette.nav.collection': 'My collection',
    'palette.nav.wishlist': 'Wishlist',
    'palette.nav.shop': 'Shop',
    'palette.nav.status': 'Sync status',
    'palette.open': 'Open',
    'palette.navigate': 'navigate',
    'palette.close': 'close',
  },
  id: {
    'aria.language': 'Ganti bahasa',
    'footer.browse': 'Jelajahi',
    'nav.browse': 'Katalog',
    'nav.groups': 'Grup',
    'nav.cardTypes': 'Jenis Kartu',
    'nav.releases': 'Rilisan',
    'nav.collection': 'Koleksi',
    'nav.shop': 'Toko',
    'nav.status': 'Status',
    'search.placeholder': 'Cari member, album, photocard...',
    'home.searchPlaceholder': 'Cari member, album, jenis kartu...',
    'footer.tagline': 'Katalog & pelacak koleksi photocard K-pop.',
    'footer.copyright': 'Hak cipta oleh',
    'footer.dataBasedOn': 'Berdasarkan data',
    'footer.tracker': 'Pelacak Photocard K-pop',
    'sync.synced': 'Tersinkron',
    'sync.cards': 'kartu',
    'sync.failed': 'Sinkron gagal',
    'sync.partial': 'Sinkron sebagian',
    'sync.stuck': 'Sinkron macet sejak',
    'tab.home': 'Beranda',
    'tab.catalog': 'Katalog',
    'tab.groups': 'Grup',
    'tab.collection': 'Koleksi',
    'home.eyebrow': 'Database photocard K-pop',
    'home.heroDescA': 'Jelajahi album PC, POB, lucky draw, dan photocard spesial — per grup, member, album, serta referensi pasar dari ',
    'cardTypes.eyebrow': 'Jelajahi jenis kartu',
    'cardTypes.title': 'Jenis kartu seperti apa?',
    'cardTypes.all': 'Semua jenis kartu',
    'releases.eyebrow': 'Jelajahi rilisan',
    'releases.title': 'Album & rilisan',
    'releases.all': 'Semua rilisan',
    'releases.cards': 'kartu',
    'trending.title': 'Photocard populer',
    'viewAll': 'Lihat semua',
    'browseAll': 'Lihat semua',
    'empty.noCards': 'Photocard tidak ditemukan.',
    'empty.hint': 'Coba grup lain atau cek kembali setelah sinkronisasi harian.',
    'empty.browseAll': 'Jelajahi semua photocard',
    'groups.eyebrow': 'Jelajahi grup',
    'groups.title': 'Telusuri per grup',
    'groups.open': 'Buka katalog',
    'groups.desc.ive': 'Album pull, POB, dan kartu fan-signed.',
    'groups.desc.aespa': 'Merch tur, lucky draw, dan kebutuhan wajib.',
    'groups.desc.h2h': 'Rilisan baru yang dilacak dari Pocamarket.',
    'movers.eyebrow': 'Pergerakan harga',
    'movers.title': 'Perubahan terbesar sejak sinkron kemarin',
    'movers.drops': 'Turun paling besar',
    'movers.risers': 'Naik paling besar',
    'movers.vs': '· harga terbaru vs sebelumnya',
    'palette.placeholder': 'Cari photocard atau buka halaman…',
    'palette.searching': 'Mencari…',
    'palette.noResults': 'Photocard tidak ditemukan untuk',
    'palette.cards': 'Photocards',
    'palette.goto': 'Buka halaman',
    'palette.nav.home': 'Beranda',
    'palette.nav.browse': 'Jelajahi photocard',
    'palette.nav.releases': 'Timeline rilisan',
    'palette.nav.collection': 'Koleksi saya',
    'palette.nav.wishlist': 'Wishlist',
    'palette.nav.shop': 'Toko',
    'palette.nav.status': 'Status sinkronisasi',
    'palette.open': 'Buka',
    'palette.navigate': 'navigasi',
    'palette.close': 'tutup',
  },
}
