export type Locale = 'en' | 'id'

/**
 * UI strings for the EN/ID toggle. Data (card names, groups, releases) stays
 * as-is in both locales.
 */
export const STRINGS: Record<Locale, Record<string, string>> = {
  en: {
    'aria.language': 'Switch language',
    'footer.browse': 'Browse',
    'nav.browse': 'Catalog',
    'nav.groups': 'Groups',
    'nav.cardTypes': 'Card Types',
    'nav.releases': 'Releases',
    'nav.collection': 'Collection',
    'nav.shop': 'Shop',
    'nav.status': 'Status',
    'search.placeholder': 'Search member, album, photocard...',
    'home.searchPlaceholder': 'Search member, album, card type...',
    'footer.tagline': 'K-pop photocard catalog & collection tracker.',
    'footer.copyright': 'Copyright by',
    'footer.dataBasedOn': 'Data based on',
    'footer.tracker': 'K-Pop Photocard Tracker',
    'sync.synced': 'Synced',
    'sync.cards': 'cards',
    'sync.failed': 'Sync failed',
    'sync.partial': 'Sync partial',
    'sync.stuck': 'Sync stuck since',
    'tab.home': 'Home',
    'tab.catalog': 'Catalog',
    'tab.groups': 'Groups',
    'tab.collection': 'Collection',
    'home.eyebrow': 'K-pop photocard database',
    'home.heroDescA': 'Explore album PCs, POBs, lucky draws and special photocards — by group, member, album, and market reference from ',
    'cardTypes.eyebrow': 'Explore by card type',
    'cardTypes.title': 'What kind of card is it?',
    'cardTypes.all': 'All card types',
    'releases.eyebrow': 'Explore releases',
    'releases.title': 'Albums & releases',
    'releases.all': 'All releases',
    'releases.cards': 'cards',
    'trending.title': 'Trending Photocards',
    'viewAll': 'View all',
    'browseAll': 'Browse all',
    'empty.noCards': 'No photocards found.',
    'empty.hint': 'Try another group or check back after the daily sync.',
    'empty.browseAll': 'Browse all photocards',
    'groups.eyebrow': 'Explore groups',
    'groups.title': 'Browse by group',
    'groups.open': 'Open catalog',
    'groups.desc.ive': 'Album pulls, POBs, and fan-signed cards.',
    'groups.desc.aespa': 'Tour merch, lucky draws, and essentials.',
    'groups.desc.h2h': 'Fresh releases tracked from Pocamarket.',
    'movers.eyebrow': 'Price movers',
    'movers.title': 'Biggest changes since yesterday’s sync',
    'movers.drops': 'Biggest drops',
    'movers.risers': 'Biggest risers',
    'movers.vs': '· latest vs previous price',
    'palette.placeholder': 'Search photocards or jump to a page…',
    'palette.searching': 'Searching…',
    'palette.noResults': 'No photocards found for',
    'palette.cards': 'Photocards',
    'palette.goto': 'Go to',
    'palette.nav.home': 'Home',
    'palette.nav.browse': 'Browse photocards',
    'palette.nav.releases': 'Releases timeline',
    'palette.nav.collection': 'My collection',
    'palette.nav.wishlist': 'Wishlist',
    'palette.nav.shop': 'Shop',
    'palette.nav.status': 'Sync status',
    'palette.open': 'Open',
    'palette.navigate': 'navigate',
    'palette.close': 'close',
    'browse.title': 'Photocard Catalog',
    'browse.loading': 'Loading…',
    'browse.eyebrow': 'Catalog',
    'browse.cardCount': 'cards',
    'browse.dataSource': 'Market reference data from',
    'browse.allStores': 'All stores',
    'browse.allTypes': 'All types',
    'browse.allMembers': 'All',
    'browse.storeLabel': 'Store',
    'browse.typeLabel': 'Card Type',
    'browse.memberLabel': 'Member',
    'browse.priceLabel': 'Price (IDR)',
    'browse.priceMin': 'Min',
    'browse.priceMax': 'Max',
    'browse.priceMinAria': 'Minimum price in IDR',
    'browse.priceMaxAria': 'Maximum price in IDR',
    'browse.clear': 'Clear filters',
    'browse.clearAll': 'Clear all',
    'browse.clearMobile': 'Clear',
    'browse.showResults': 'Show results',
    'browse.filters': 'Filters',
    'browse.filtersDesc': 'Narrow results by member, card type, and price.',
    'browse.empty.title': 'No photocards match these filters.',
    'browse.empty.hint': 'Try another group, member, or card type.',
    'browse.error.title': 'Unable to load photocards.',
    'browse.error.hint': 'Please try again.',
    'browse.error.retry': 'Retry',
    'browse.search.placeholder': 'Search member, group, album, card type, store...',
    'browse.search.aria': 'Search photocards',
    'browse.sort.aria': 'Sort',
    'browse.sort.popular': 'Popular',
    'browse.sort.recent': 'Recent',
    'browse.sort.priceAsc': 'Price: low to high',
    'browse.sort.priceDesc': 'Price: high to low',
    'browse.sort.stock': 'Most in stock',
    'browse.sort.name': 'Name A-Z',
    'browse.sort.wishlist': 'Most wishlisted',
    'browse.groupLabel': 'Group',
    'browse.memberChipAll': 'All',
    'browse.activeFilters': '{count} filters',
    'browse.prev': 'Prev',
    'browse.next': 'Next',
    'browse.pageOf': 'Page {current} of {total}',
    'browse.pageOfCards': 'Page {current} of {total} · {count} cards',
    'browse.stores.empty': 'No store data yet.',
    'browse.member.aria': 'Clear member {name}',
    'browse.cardType.aria': 'Clear card type {name}',
    'browse.release.aria': 'Clear release filter',
    'browse.store.aria': 'Clear store {name}',
    'browse.price.aria': 'Clear price filter',
    'card.type': 'Type',
    'card.group': 'Group',
    'card.member': 'Member',
    'card.albumRelease': 'Album / release',
    'card.store': 'Store',
    'card.event': 'Event',
    'card.listedAs': 'Listed as',
    'card.marketReference': 'Market reference',
    'card.dataSource': 'Data source · Pocamarket',
    'card.notAvailable': 'Not available',
    'card.viewOnPocamarket': 'View on Pocamarket',
    'card.wishlist': 'Wishlist',
    'card.wishlisted': 'Wishlisted',
    'card.addToCollection': 'Add to Collection',
    'card.inCollection': 'In Collection',
    'card.whatIsThis': 'What is this?',
    'card.whatIsType': 'What is {type}?',
    'card.browseMore': 'Browse more {type}',
    'card.priceHistory': 'Price History',
    'card.priceHistoryEmpty': "Price history isn't available for this card yet.",
    'card.priceHistoryLow': 'Low: ${price}',
    'card.priceHistoryHigh': 'High: ${price}',
    'card.priceChangeSince': 'since last snapshot',
    'card.info.title': 'Card information',
    'card.release.title': 'Release information',
    'card.release.source': 'Source · {source}',
    'card.release.released': 'Released {date}',
    'card.release.tracks': 'Tracks',
    'card.release.moreTracks': '+ {count} more tracks',
    'card.addDialog.title': 'Add to Collection',
    'card.addDialog.desc': 'Save this photocard to your owned collection. Use the heart button for wishlist.',
    'card.addDialog.priceLabel': 'Bought Price (USD)',
    'card.addDialog.pricePlaceholder': 'Optional',
    'card.addDialog.cancel': 'Cancel',
    'card.addDialog.add': 'Add',
    'card.addDialog.adding': 'Adding...',
    'card.error.title': 'Unable to load this photocard.',
    'card.error.back': 'Back to browse',
    'card.notFound': 'Photocard not found.',
    'card.unableLoad': 'Unable to load this photocard.',
    'card.noType': 'Album',
  },
  id: {
    'aria.language': 'Ganti bahasa',
    'footer.browse': 'Jelajahi',
    'nav.browse': 'Katalog',
    'nav.groups': 'Grup',
    'nav.cardTypes': 'Jenis Kartu',
    'nav.releases': 'Rilisan',
    'nav.collection': 'Koleksi',
    'nav.shop': 'Toko',
    'nav.status': 'Status',
    'search.placeholder': 'Cari member, album, photocard...',
    'home.searchPlaceholder': 'Cari member, album, jenis kartu...',
    'footer.tagline': 'Katalog & pelacak koleksi photocard K-pop.',
    'footer.copyright': 'Hak cipta oleh',
    'footer.dataBasedOn': 'Berdasarkan data',
    'footer.tracker': 'Pelacak Photocard K-pop',
    'sync.synced': 'Tersinkron',
    'sync.cards': 'kartu',
    'sync.failed': 'Sinkron gagal',
    'sync.partial': 'Sinkron sebagian',
    'sync.stuck': 'Sinkron macet sejak',
    'tab.home': 'Beranda',
    'tab.catalog': 'Katalog',
    'tab.groups': 'Grup',
    'tab.collection': 'Koleksi',
    'home.eyebrow': 'Database photocard K-pop',
    'home.heroDescA': 'Jelajahi album PC, POB, lucky draw, dan photocard spesial — per grup, member, album, serta referensi pasar dari ',
    'cardTypes.eyebrow': 'Jelajahi jenis kartu',
    'cardTypes.title': 'Jenis kartu seperti apa?',
    'cardTypes.all': 'Semua jenis kartu',
    'releases.eyebrow': 'Jelajahi rilisan',
    'releases.title': 'Album & rilisan',
    'releases.all': 'Semua rilisan',
    'releases.cards': 'kartu',
    'trending.title': 'Photocard populer',
    'viewAll': 'Lihat semua',
    'browseAll': 'Lihat semua',
    'empty.noCards': 'Photocard tidak ditemukan.',
    'empty.hint': 'Coba grup lain atau cek kembali setelah sinkronisasi harian.',
    'empty.browseAll': 'Jelajahi semua photocard',
    'groups.eyebrow': 'Jelajahi grup',
    'groups.title': 'Telusuri per grup',
    'groups.open': 'Buka katalog',
    'groups.desc.ive': 'Album pull, POB, dan kartu fan-signed.',
    'groups.desc.aespa': 'Merch tur, lucky draw, dan kebutuhan wajib.',
    'groups.desc.h2h': 'Rilisan baru yang dilacak dari Pocamarket.',
    'movers.eyebrow': 'Pergerakan harga',
    'movers.title': 'Perubahan terbesar sejak sinkron kemarin',
    'movers.drops': 'Turun paling besar',
    'movers.risers': 'Naik paling besar',
    'movers.vs': '· harga terbaru vs sebelumnya',
    'palette.placeholder': 'Cari photocard atau buka halaman…',
    'palette.searching': 'Mencari…',
    'palette.noResults': 'Photocard tidak ditemukan untuk',
    'palette.cards': 'Photocards',
    'palette.goto': 'Buka halaman',
    'palette.nav.home': 'Beranda',
    'palette.nav.browse': 'Jelajahi photocard',
    'palette.nav.releases': 'Timeline rilisan',
    'palette.nav.collection': 'Koleksi saya',
    'palette.nav.wishlist': 'Wishlist',
    'palette.nav.shop': 'Toko',
    'palette.nav.status': 'Status sinkronisasi',
    'palette.open': 'Buka',
    'palette.navigate': 'navigasi',
    'palette.close': 'tutup',
    'browse.title': 'Katalog Photocard',
    'browse.loading': 'Memuat…',
    'browse.eyebrow': 'Katalog',
    'browse.cardCount': 'kartu',
    'browse.dataSource': 'Data referensi pasar dari',
    'browse.allStores': 'Semua toko',
    'browse.allTypes': 'Semua jenis',
    'browse.allMembers': 'Semua',
    'browse.storeLabel': 'Toko',
    'browse.typeLabel': 'Jenis Kartu',
    'browse.memberLabel': 'Member',
    'browse.priceLabel': 'Harga (IDR)',
    'browse.priceMin': 'Min',
    'browse.priceMax': 'Maks',
    'browse.priceMinAria': 'Harga minimum dalam IDR',
    'browse.priceMaxAria': 'Harga maksimum dalam IDR',
    'browse.clear': 'Hapus filter',
    'browse.clearAll': 'Hapus semua',
    'browse.clearMobile': 'Hapus',
    'browse.showResults': 'Tampilkan hasil',
    'browse.filters': 'Filter',
    'browse.filtersDesc': 'Saring hasil berdasarkan member, jenis kartu, dan harga.',
    'browse.empty.title': 'Tidak ada photocard yang cocok dengan filter ini.',
    'browse.empty.hint': 'Coba grup, member, atau jenis kartu lain.',
    'browse.error.title': 'Gagal memuat photocard.',
    'browse.error.hint': 'Silakan coba lagi.',
    'browse.error.retry': 'Coba lagi',
    'browse.search.placeholder': 'Cari member, grup, album, jenis kartu, toko...',
    'browse.search.aria': 'Cari photocard',
    'browse.sort.aria': 'Urutkan',
    'browse.sort.popular': 'Populer',
    'browse.sort.recent': 'Terbaru',
    'browse.sort.priceAsc': 'Harga: rendah ke tinggi',
    'browse.sort.priceDesc': 'Harga: tinggi ke rendah',
    'browse.sort.stock': 'Stok terbanyak',
    'browse.sort.name': 'Nama A-Z',
    'browse.sort.wishlist': 'Paling banyak di-wishlist',
    'browse.groupLabel': 'Grup',
    'browse.memberChipAll': 'Semua',
    'browse.activeFilters': '{count} filter',
    'browse.prev': 'Sebelumnya',
    'browse.next': 'Berikutnya',
    'browse.pageOf': 'Halaman {current} dari {total}',
    'browse.pageOfCards': 'Halaman {current} dari {total} · {count} kartu',
    'browse.stores.empty': 'Belum ada data toko.',
    'browse.member.aria': 'Hapus filter member {name}',
    'browse.cardType.aria': 'Hapus filter jenis kartu {name}',
    'browse.release.aria': 'Hapus filter rilisan',
    'browse.store.aria': 'Hapus filter toko {name}',
    'browse.price.aria': 'Hapus filter harga',
    'card.type': 'Jenis',
    'card.group': 'Grup',
    'card.member': 'Member',
    'card.albumRelease': 'Album / rilisan',
    'card.store': 'Toko',
    'card.event': 'Event',
    'card.listedAs': 'Terdaftar sebagai',
    'card.marketReference': 'Referensi pasar',
    'card.dataSource': 'Sumber data · Pocamarket',
    'card.notAvailable': 'Tidak tersedia',
    'card.viewOnPocamarket': 'Lihat di Pocamarket',
    'card.wishlist': 'Wishlist',
    'card.wishlisted': 'Di-wishlist',
    'card.addToCollection': 'Tambah ke Koleksi',
    'card.inCollection': 'Ada di Koleksi',
    'card.whatIsThis': 'Apa ini?',
    'card.whatIsType': 'Apa itu {type}?',
    'card.browseMore': 'Lihat {type} lainnya',
    'card.priceHistory': 'Riwayat Harga',
    'card.priceHistoryEmpty': 'Riwayat harga belum tersedia untuk kartu ini.',
    'card.priceHistoryLow': 'Terendah: ${price}',
    'card.priceHistoryHigh': 'Tertinggi: ${price}',
    'card.priceChangeSince': 'sejak pembaruan terakhir',
    'card.info.title': 'Informasi kartu',
    'card.release.title': 'Informasi rilisan',
    'card.release.source': 'Sumber · {source}',
    'card.release.released': 'Rilis {date}',
    'card.release.tracks': 'Daftar lagu',
    'card.release.moreTracks': '+ {count} lagu lainnya',
    'card.addDialog.title': 'Tambah ke Koleksi',
    'card.addDialog.desc': 'Simpan photocard ini ke koleksi milikmu. Gunakan tombol hati untuk wishlist.',
    'card.addDialog.priceLabel': 'Harga Beli (USD)',
    'card.addDialog.pricePlaceholder': 'Opsional',
    'card.addDialog.cancel': 'Batal',
    'card.addDialog.add': 'Tambah',
    'card.addDialog.adding': 'Menambahkan...',
    'card.error.title': 'Gagal memuat photocard ini.',
    'card.error.back': 'Kembali ke beranda',
    'card.notFound': 'Photocard tidak ditemukan.',
    'card.unableLoad': 'Gagal memuat photocard ini.',
    'card.noType': 'Album',
  },
}
